VendM.Web/Areas/Basics/Controllers/PayMentController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using VendM.Core;
using VendM.Model.DataModelDto;
using VendM.Model.EnumModel;
using VendM.Service;
using VendM.Service.BasicsService;
using VendM.Web.Authorization;
using VendM.Web.BaseApplication;
using VendM.Web.Models;
namespace VendM.Web.Areas.Basics.Controllers
{
    public class PayMentController : ServicedController<PayMentService>
    {
        #region VendM.Web.Areas.Basics.Controllers
        /// <summary>
        /// 首页
        /// </summary>
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetPayMentGrid(int limit, int offset, string sort, string sortOrder,string paymentcode, string paymentname)
        {
            TablePageParameter gp = new TablePageParameter() { Limit = limit, Offset = offset, SortName = sort, SortOrder = sortOrder };
            List<PayMentDto> machineList = Service.GetPayMentGrid(gp, paymentcode, paymentname);
            return Json(new { total = gp.TotalCount, rows = machineList }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 新建
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.StatusType = GetSelectList(typeof(PaymentEnum), true);
            return View();
        }

        /// <summary>
        /// Market
        /// </summary>
        /// <param name="emptyKey"></param>
        /// <param name="emptyValue"></param>
        /// <param name="isAll"></param>
        /// <returns></returns>
        public List<SelectListItem> GetStoreSelectList(string emptyKey, string emptyValue, bool isAll = false)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            if (emptyKey != null)
            {
                listItems.Add(new SelectListItem { Text = emptyValue, Value = emptyKey });
            }
            List<StoreDto> lists = new StoreService().GetStoreGrid();
            foreach (var item in lists)
            {
                listItems.Add(new SelectListItem { Text = item.Name, Value = item.Id.ToString() });
            }
            return listItems;
        }

        [HttpPost]
        public ActionResult Add(PayMentDto PayMentdto)
        {
            ResultJsonInfo resultJsonInfo = new ResultJsonInfo() { Data = "", ErrorMsg = "", Success = true };
            try
            {
                if (ModelState.IsValid)
                {
                    PayMentdto.CreateUser = ServiceHelper.GetCurrentUser().UserName;
                    PayMentdto.CredateTime = DateTime.Now;
                    PayMentdto.UpdateUser = ServiceHelper.GetCurrentUser().UserName;
                    PayMentdto.UpdateTime = DateTime.Now;
                }
                if (Service.Add(PayMentdto))
                {
                    return this.Ajax_JGClose();
                }
                return View();
            }
            catch (Exception ex)
            {
                string msg = ex.Message;
                throw;
            }
        }
        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var entity = Service.Find(id);
            ViewBag.StatusType = GetSelectList(typeof(PaymentEnum), true);
            ViewData.Model = entity;
            return View();
        }
        [HttpPost]
        public ActionResult Edit(PayMentDto PayMentdto)
        {
            string errorMsg = "";
            if (ModelState.IsValid)
            {
                PayMentdto.UpdateUser = ServiceHelper.GetCurrentUser().LoginName;
                PayMentdto.UpdateTime = DateTime.Now.Date;
                if (Service.Update(PayMentdto))
                {
                    return this.Ajax_JGClose();
                }
            }
            @ViewBag.errorMsg = errorMsg;
            return View();
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpPost]
        public JsonResult Delete(string ids)
        {
            ResultJsonInfo resultJsonInfo = new ResultJsonInfo() { Data = "", ErrorMsg = "", Success = true };
            try
            {
                if (!Service.Deletes(ids, ServiceHelper.GetCurrentUser().LoginName))
                {
                    resultJsonInfo.Success = false;
                }
            }
            catch (Exception ex)
            {
                resultJsonInfo.Success = false;
                resultJsonInfo.ErrorMsg = ex.Message;
            }
            return Json(resultJsonInfo, JsonRequestBehavior.AllowGet);
        }

        public string ValidateName(string PaymentName)
        {
            try
            {
                if (!Service.IsExist(PaymentName))
                    return "true";
            }
            catch (Exception)
            {

            }
            return "false";
        }
        #endregion
    }
}

VendM.Web/Areas/Basics/Views/PayMent/Add.cshtml
@model VendM.Model.DataModelDto.PayMentDto
@{
    ViewBag.Title = "Add";
}
@using (Html.BeginForm("Add", "PayMent", FormMethod.Post))
{
<div style=" margin:15px; border:1px">
    <div class="form-group">
        <label for="name">支付名称</label>
        @Html.TextBoxFor(m => m.PaymentName, new { @class = "form-control", placeholder = "支付名称", required = "required" })
    </div>
    <div class="form-group">
        <label for="name">支付Code</label>
        @Html.TextBoxFor(m => m.PaymentCode, new { @class = "form-control", placeholder = "Code", required = "required" })
    </div>
    <div class="form-group">
        <label for="name">状态</label>
        @Html.DropDownListFor(m => m.Status, (IEnumerable<SelectListItem>)ViewBag.StatusType, new { @class = "form-control" })
    </div>
    <div class="form-group" style="color:red ">
        @ViewBag.errorMsg
    </div>
    <div>
        <div>
            <button type="submit" class="btn btn-primary btn-primary-subbtn">提交</button>
        </div>
    </div>
</div>
}
<script>
    /*自定义validate*/
    var rules = {
        PaymentName: {
            required: true,
            remote: "/PayMent/ValidateName"
        },
        PaymentCode: "required",
    },
        messages = {
            PaymentName: {
                required: "请输入支付名稱",
                remote: "已存在支付名稱"
            },
            PaymentCode: {
                required: "请输入支付Code"
            }
        };
        // 在键盘按下并释放及提交后验证提交表单
        $("form").validate({
            rules: rules,
            messages: messages
        });
</script>

VendM.Web/Areas/Basics/Views/PayMent/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
@model VendM.Model.DataModelDto.PayMentDto
<script type="text/javascript">
    /*自定义validate*/
    var rules = {
        PaymentName: {
            required: true,
        },
        PaymentCode: "required",
        Charge: {
            required: true,
        },
        Fee: {
            required: true,
        },
    },
        messages = {
            PaymentName: {
                required: "请输入支付名稱",
            },
            PaymentCode: {
                required: "请输入支付Code"
            }
        };
    $(document).ready(function () {
        // 在键盘按下并释放及提交后验证提交表单
        $("form").validate({
            rules: rules,
            messages: messages
        });
    });
   
</script>
@using (Html.BeginForm())
{<div style=" margin:15px; border:1px">
        <div class="form-group">
            <label for="name">支付名称</label>
            @Html.TextBoxFor(m => m.PaymentName, Model.PaymentName, new { @class = "form-control", placeholder = "请输入支付名称", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">支付Code</label>
            @Html.TextBoxFor(m => m.PaymentCode, Model.PaymentCode, new { @class = "form-control", placeholder = "请输支付Code", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">状态</label>
            @Html.DropDownListFor(m => m.Status, (IEnumerable<SelectListItem>)ViewBag.StatusType, new { @class = "form-control" })
        </div>
        <div>
            <button type="submit" class="btn btn-primary btn-primary-subbtn">提交</button>
        </div>
    </div>
}

VendM.Web/Areas/Basics/Views/PayMent/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/layer/layui.js"></script>
<link href="~/Scripts/layer/layui.css" rel="stylesheet" />
<div class="page animation-fade">
    <div class="page-content">
        <!--高级检索部分-->
        <div class="panel" id="panelSearch">
            <div class="panel-heading">
                <h3 class="panel-title">高级检索</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-3 pannel-box">
                    <h4 class="example-title h4-box">支付名称</h4>
                    <input type="text" class="form-control input-box" id="paymentName" placeholder="请输入支付名称">
                </div>
                <div class="col-sm-3 pannel-box">
                    <h4 class="example-title h4-box">支付Code</h4>
                    <input type="text" class="form-control input-box" id="paymentCode" placeholder="请输入支付Code">
                </div>
            </div>
        </div>
        <!--列表-->
        <div class="panel">
            <div class="panel-heading">
                <div class="col-sm-12 pl-25 pr-25 pt-15 pb-10">
                    <button type="button" class="btn btn-primary" onclick="window.location=window.location">
                        <i class="fa fa-rotate-right"></i>&nbsp;刷新
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Search" name="search" id="search">
                        <i class="fa fa-search"></i>&nbsp;查询
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Add" name="add" id="add">
                        <i class="fa fa-plus"></i>&nbsp;添加
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Edit" name="edit" id="edit">
                        <i class="fa fa-pencil"></i>&nbsp;修改
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Delete" name="delete" id="delete">
                        <i class="fa fa-trash"></i>&nbsp;删除
                    </button>
                </div>
            </div>
            <div class="panel-body container-fluid pb-0">
                <!--表格-->
                <table class="bootstrap-table" data-show-columns="false" id="PaymentTable"></table>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        //查询
        $("#search").on('click', function () {
            $("#PaymentTable").bootstrapTable('refresh', { url: '/PayMent/GetPaymentGrid' });
        });
        //添加
        $("#add").on('click', function () {
            CreatePayment();
        });
        //修改
        $("#edit").on('click', function () {
            var id = $.map($('#PaymentTable').bootstrapTable('getSelections'), function (row) {
                return row.Id;
            });
            if (id.length != 1) {
                layer.msg('请选中一行', {
                    time: 4000,
                });
            } else {
                EditPayment(id);
            }
        });
        //删除
        $("#delete").on('click', function () {
            var ids = $.map($('#PaymentTable').bootstrapTable('getSelections'), function (row) {
                return row.Id;
            });
            if (ids.length < 1) {
                layer.msg('请至少选中一行', {
                    time: 4000, //20s后自动关闭
                });
            } else {
                Delete(ids.join(","));
            }
        });
        //2.初始化Button的点击事件
        var oButtonInit = new ButtonInit();
        oButtonInit.Init();
        //用户
        //1.初始化商户Table
        var PaymentTablets = new PaymentTableInit();
        PaymentTablets.Init();
    });
    var ButtonInit = function () {
        var oInit = new Object();
        var postdata = {};
        oInit.Init = function () {
            //初始化页面上面的按钮事件
        };
        return oInit;
    };
    var PaymentTableInit = function () {
        var oTableInit = new Object();
        //初始化Table
        oTableInit.Init = function () {
            $('#PaymentTable').bootstrapTable({
                url: '/PayMent/GetPaymentGrid',
                ajaxOptions: { async: true, timeout: 10000 },
                method: 'get',
                //toolbar: '#toolbar',              //工具按钮用哪个容器
                striped: false,
                toolbar: false,                     //是否显示行间隔色
                cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                pagination: true,                   //是否显示分页（*）
                silentSort: true,
                sortStable: true,
                sortable: true,                     //是否启用排序
                sortOrder: "asc",                   //排序方式
                queryParams: oTableInit.queryParams,//这里的键的名字和控制器的变量名必须一致，这边改动，控制器也需要改成一样的
                sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
                pageNumber: 1,                      //初始化加载第一页，默认第一页,并记录
                pageSize: 10,                       //每页的记录行数（*）
                pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                search: false,                      //是否显示表格搜索
                strictSearch: true,
                showColumns: false,                  //是否显示所有的列（选择显示的列）
                showRefresh: false,                  //是否显示刷新按钮
                minimumCountColumns: 2,             //最少允许的列数
                clickToSelect: true,                //是否启用点击选中行
                height: "auto",                     //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                uniqueId: "Id",                     //每一行的唯一标识，一般为主键列
                showToggle: false,                  //是否显示详细视图和列表视图的切换按钮
                cardView: false,                    //是否显示详细视图
                detailView: false,                  //是否显示父子表
                columns: [
                    {
                        checkbox: true,
                        visible: true              //是否显示复选框
                    },
                    {
                        field: 'Id',
                        title: '序号',
                        sortable: true
                    },
                    {
                        field: 'PaymentName',
                        title: '支付名称',
                        sortable: true
                    },
                    {
                        field: 'PaymentCode',
                        title: '支付Code'
                    },
                    {
                        field: 'StatusName',
                        title: '状态'
                        //formatter: function (value, row, index) {
                        //    debugger;
                        //    var state = "";
                        //    if (value == "1") {
                        //        state = "<input type='checkbox' value='" + value + "' id='status' lay-filter='Status' checked='checked' name='Status'  lay-skin='switch' lay-text='开启|关闭' >";
                        //    }
                        //    else {
                        //        state = "<input type='checkbox' value='" + value + "' id='status' lay-filter='Status'  name='Status'  lay-skin='switch' lay-text='开启|关闭' >";
                        //    }
                        //    return state;
                        //}
                    }
                ]
            });
        };
        //得到查询的参数
        oTableInit.queryParams = function (params) {
            var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
                limit: params.limit,   //页面大小
                offset: params.offset,  //页码
                sort: params.sort,      //排序列名
                sortOrder: params.order, //排位命令（desc，asc）
                paymentcode: $("#paymentCode").val(),
                paymentname: $("#paymentName").val()
            };
            return temp;
        };
        return oTableInit;
    };
</script>

<script>
    var CreatePayment = function () {
        layer.open({
            type: 2,
            title: '添加支付类型',
            shadeClose: true,
            shade: 0.8,
            area: ['25%', '45%'],
            content: 'Add'
        })
    }
    var EditPayment = function (id) {
        layer.open({
            type: 2,
            title: '编辑支付类型',
            shadeClose: true,
            shade: 0.8,
            area: ['25%', '45%'],
            content: 'Edit?id=' + id
        })
    }
    //删除
    var Delete = function (ids) {
        layer.confirm('您确定要删除吗？', {
            title: '提示',
            move: false,
            anim: 1, //默认动画风格
            btn: ['确定', '取消'] //按钮
        }, function () {
            $.ajax({
                type: 'Post',
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                data: JSON.stringify({ ids: ids }),
                async: true,
                url: 'Delete',
                success: function (result) {
                    if (result.Success) {
                        layer.closeAll('dialog');
                        layer.msg('删除成功！', {
                            time: 2000,
                        });
                        $("#PaymentTable").bootstrapTable('refresh', { url: '/PayMent/GetPaymentGrid' });
                    } else {
                        layer.open({
                            title: '提示',
                            content: '删除失败！',
                            move: false,
                            btn: "知道了"
                        });
                    }
                },
                error: function (result) {
                    console.log(result)
                }
            })
        });
    };
     //导出
    var Export = function (ids) {
        $.ajax({
            type: "Post",
            url: '@Url.Action("ExportExcel", "Payment", new { area = "" })',
            dataType: "json",
            data: {
                ids: ids,
                profileId: $("#profileId").val(),
                merchantName: $("#merchantName").val()
            },
            success: function (result) {
                if (result.Success) {
                    window.location.target = "_blank";
                    window.location.href = result.Data;
                } else {
                    layer.open({
                        title: '提示',
                        content: result.ErrorMsg,
                        move: false,
                        btn: "知道了"
                    });
                }
            }
        })
    }
</script>