VendM.Web/Areas/Basics/Controllers/MachineDetailController.cs
using System;
using System.Collections.Generic;
using VendM.Service;
using System.Web.Mvc;
using VendM.Core;
using VendM.Model.DataModelDto;
using VendM.Model.DataModelDto.Product;
using VendM.Web.Authorization;
using VendM.Web.BaseApplication;
using VendM.Web.Models;

namespace VendM.Web.Areas.Basics.Controllers
{
    public class MachineDetailController : ServicedController<MachineDetailService>
    {
        #region VendM.Web.Areas.Basics.Controllers
        /// <summary>
        /// 首页
        /// </summary>
        [HttpGet]
        public ActionResult Index()
        {
            ViewData["ProductNoList"] = GetProductNoSelectList("-1", "请选择");
            return View();
        }
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetMachineDetailGrid(int limit, int offset, string sort, string sortOrder, string machinemame, string machinenumber,string productid)
        {
            TablePageParameter gp = new TablePageParameter() { Limit = limit, Offset = offset, SortName = sort, SortOrder = sortOrder };
            List<MachineDetailDto> MachineDetailList = Service.GetMachineDetailGrid(gp, machinemame, machinenumber, productid);
            return Json(new { total = gp.TotalCount, rows = MachineDetailList }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新建
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult Add()
        {
            ViewData["MachineNoList"] = GetMachineNoSelectList("-1", "请选择");
            ViewData["ProductNoList"] = GetProductNoSelectList("-1", "请选择");
            return View();
        }

        [HttpPost]
        public ActionResult Add(MachineDetailDto MachineDetaildto)
        {
            ResultJsonInfo resultJsonInfo = new ResultJsonInfo() { Data = "", ErrorMsg = "", Success = true };
            try
            {
                if (ModelState.IsValid)
                {
                    if (!Service.CheckChannel(MachineDetaildto.MachineId, MachineDetaildto.PassageNumber))
                    {
                        if (Service.AddMachineDetail(MachineDetaildto, ServiceHelper.GetCurrentUser().UserName))
                        {
                            return this.Ajax_JGClose();
                        }
                    }
                    else
                    {
                        return Content("<script>alert('該機器的通道已存在');history.go(-1);</script>");
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                string msg = ex.Message;
                throw;
            }
        }

        /// <summary>
        /// 機器編號
        /// </summary>
        /// <param name="emptyKey"></param>
        /// <param name="emptyValue"></param>
        /// <param name="isAll"></param>
        /// <returns></returns>
        public List<SelectListItem> GetMachineNoSelectList(string emptyKey, string emptyValue, bool isAll = false)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            if (emptyKey != null)
            {
                listItems.Add(new SelectListItem { Text = emptyValue, Value = emptyKey });
            }
            List<MachineDto> lists = new Service.MachineService().GetMachineGrid();
            foreach (var item in lists)
            {
                listItems.Add(new SelectListItem { Text = item.MachineNo, Value = item.Id.ToString() });
            }
            return listItems;
        }


        /// <summary>
        /// 產品名稱
        /// </summary>
        /// <param name="emptyKey"></param>
        /// <param name="emptyValue"></param>
        /// <param name="isAll"></param>
        /// <returns></returns>
        public List<SelectListItem> GetProductNoSelectList(string emptyKey, string emptyValue, bool isAll = false)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            if (emptyKey != null)
            {
                listItems.Add(new SelectListItem { Text = emptyValue, Value = emptyKey });
            }
            List<ProductDto> lists = Service.GetProductGrid();
            foreach (var item in lists)
            {
                listItems.Add(new SelectListItem { Text = item.ProductName_CH, Value = item.Id.ToString() });
            }
            return listItems;
        }



        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var entity = Service.Get(id);
            ViewData["MachineNoList"] = GetMachineNoSelectList("-1", "请选择");
            ViewData["ProductNoList"] = GetProductNoSelectList("-1", "请选择");
            ViewData.Model = entity;
            return View();
        }
        [HttpPost]
        public ActionResult Edit(MachineDetailDto MachineDetaildto)
        {
            string errorMsg = "";
            if (ModelState.IsValid)
            {
                MachineDetaildto.UpdateUser = ServiceHelper.GetCurrentUser().LoginName;
                MachineDetaildto.UpdateTime = DateTime.Now;
                if (Service.Update(MachineDetaildto,ref errorMsg))
                {
                    return this.Ajax_JGClose();
                }
            }
           
            ViewData["MachineNoList"] = GetMachineNoSelectList("-1", "请选择");
            ViewData["ProductNoList"] = GetProductNoSelectList("-1", "请选择");
            ViewData.Model = MachineDetaildto;
            if (!string.IsNullOrEmpty(errorMsg))
            {
                return Content($"<script>alert('{errorMsg}');history.go(-1);</script>");
            }
            else
            {
                return Content($"<script>alert('内部服务器错误!');history.go(-1);</script>");
            }
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpPost]
        public JsonResult Delete(string ids)
        {
            ResultJsonInfo resultJsonInfo = new ResultJsonInfo() { Data = "", ErrorMsg = "", Success = true };
            try
            {
                if (!Service.Deletes(ids, ServiceHelper.GetCurrentUser().LoginName))
                {
                    resultJsonInfo.Success = false;
                    resultJsonInfo.Data = "请先清空机器通道的货存";
                }
            }
            catch (Exception ex)
            {
                resultJsonInfo.Success = false;
                resultJsonInfo.ErrorMsg = ex.Message;
            }
            return Json(resultJsonInfo, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

VendM.Web/Areas/Basics/Views/MachineDetail/Add.cshtml
@model VendM.Model.DataModelDto.MachineDetailDto

@{
    ViewBag.Title = "Add";
}
@using (Html.BeginForm("Add", "MachineDetail", FormMethod.Post))
{
    <div style="margin: 15px; border: 1px">
        <div class="form-group">
            <label for="name">機器編號</label>
            @Html.DropDownListFor(m => m.MachineId, ViewData["MachineNoList"] as List<SelectListItem>, new { @class = "form-control", placeholder = "機器編號", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">通道編號</label>
            @Html.TextBoxFor(m => m.PassageNumber, new { @class = "form-control", placeholder = "通道編號", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">商品名稱</label>
            @Html.DropDownListFor(m => m.ProductId, ViewData["ProductNoList"] as List<SelectListItem>, new { @class = "form-control", placeholder = "商品名稱", required = "required" })
        </div>
        <div>
            <button type="submit" style="width: 100%;" class="btn btn-primary btn-primary-subbtn">提交</button>
        </div>
    </div>
}
<script>
    /*自定义validate*/
    rules = {
        MachineId: {
            required: true,
            min:0
        },
        PassageNumber: {
            required: true
        }
        ,
        ProductId: {
            required: true,
            min:0
        }
    },
        messages = {
            MachineId: {
                required: "请输入機器編號",
                min:"请输入機器編號"
            },
            PassageNumber: {
                required: "请输入您的通道編號"
        }
        ,
            ProductId: {
                required: "商品編號不存在",
                min: "商品編號不存在"
            }
        };
    $(document).ready(function () {
        // 在键盘按下并释放及提交后验证提交表单
        $("form").validate({
            rules: rules,
            messages: messages
        });
    });
</script>

VendM.Web/Areas/Basics/Views/MachineDetail/Edit.cshtml
@model VendM.Model.DataModelDto.MachineDetailDto

@{
    ViewBag.Title = "Edit";
}

    <script>
        /*自定义validate*/
        rules = {
            MachineId: {
                required: true,
                min: 0
            },
            PassageNumber: {
                required: true
            }
            ,
            ProductId: {
                required: true,
                min: 0
            }
        },
            messages = {
                MachineId: {
                    required: "请输入機器編號",
                    min: "请输入機器編號"
                },
                PassageNumber: {
                    required: "请输入您的通道編號"
                }
                ,
                ProductId: {
                    required: "商品編號不存在",
                    min: "商品編號不存在"
                }
            };
        $(document).ready(function () {
            // 在键盘按下并释放及提交后验证提交表单
            $("form").validate({
                rules: rules,
                messages: messages
            });
        });
    </script>
@using (Html.BeginForm())
{
<div style="margin: 15px; border: 1px">
    <div class="form-group">
        <label for="name">機器編號</label>
        @Html.DropDownListFor(m => m.MachineId, ViewData["MachineNoList"] as List<SelectListItem>, new { @class = "form-control", placeholder = "機器編號", required = "required" })
    </div>
    <div class="form-group">
        <label for="name">通道編號</label>
        @Html.TextBoxFor(m => m.PassageNumber, new { @class = "form-control", placeholder = "通道編號", required = "required" })
    </div>
    <div class="form-group">
        <label for="name">商品名稱</label>
        @Html.DropDownListFor(m => m.ProductId, ViewData["ProductNoList"] as List<SelectListItem>, new { @class = "form-control", placeholder = "商品名稱", required = "required" })
    </div>
    <div>
        <button type="submit" class="btn btn-primary btn-primary-subbtn">提交</button>
    </div>
</div>
}

VendM.Web/Areas/Basics/Views/MachineDetail/Index.cshtml
@model VendM.Model.DataModelDto.MachineDetailDto

@{
    ViewBag.Title = "Index";
}
<div class="page animation-fade">
    <div class="page-content">
        <!--高级检索部分-->
        <div class="panel" id="panelSearch">
            <div class="panel-heading">
                <h3 class="panel-title">高级检索</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-3 pannel-box">
                    <h4 class="example-title h4-box">机器名称</h4>
                    <input type="text" class="form-control input-box" id="MachineName" placeholder="请输入机器名称">
                </div>
                <div class="col-sm-3 pannel-box">
                    <h4 class="example-title h4-box">机器编号</h4>
                    <input type="text" class="form-control input-box" id="MachineNumber" placeholder="请输入机器编号">
                </div>
                <div class="col-sm-3 pannel-box">
                    <h4 class="example-title h4-box" style="width:70px;">商品名称</h4>
                    @Html.DropDownListFor(m => m.ProductId, ViewData["ProductNoList"] as List<SelectListItem>, new { @class = "form-control", placeholder = "商品名稱", required = "required" })
                </div>
            </div>
        </div>
        <!--列表-->
        <div class="panel">
            <div class="panel-heading">
                <div class="col-sm-12 pl-25 pr-25 pt-15 pb-10">
                    <button type="button" class="btn btn-primary" onclick="window.location=window.location">
                        <i class="fa fa-rotate-right"></i>&nbsp;刷新
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Search" name="search" id="search">
                        <i class="fa fa-search"></i>&nbsp;查询
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Add" name="add" id="add">
                        <i class="fa fa-plus"></i>&nbsp;添加
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Edit" name="edit" id="edit">
                        <i class="fa fa-pencil"></i>&nbsp;修改
                    </button>
                    <button type="button" class="btn btn-primary" data-power="Delete" name="delete" id="delete">
                        <i class="fa fa-trash"></i>&nbsp;删除
                    </button>
                    @*<a class="btn btn-primary" target="_blank" href="" data-power="GetExcel" name="getExcel" id="exportExcel">
                            <i class="fa fa-file-excel-o"></i>&nbsp;导出 Excel
                        </a>*@
                </div>
            </div>
            <div class="panel-body container-fluid pb-0">
                <!--表格-->
                <table class="bootstrap-table" data-show-columns="false" id="MachineDetailTable"></table>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $("#search").on('click',
            function () {
                $("#MachineDetailTable").bootstrapTable('refresh', { url: '/MachineDetail/GetMachineDetailGrid' });
            });
        //添加
        $("#add").on('click', function () {
            CreateMachineDetail();
        });
        //修改
        $("#edit").on('click', function () {
            var id = $.map($('#MachineDetailTable').bootstrapTable('getSelections'), function (row) {
                return row.Id;
            });
            if (id.length != 1) {
                layer.msg('请选中一行', {
                    time: 4000,
                });
            } else {
                EditMachineDetail(id);
            }
        });
        //删除
        $("#delete").on('click', function () {
            var ids = $.map($('#MachineDetailTable').bootstrapTable('getSelections'), function (row) {
                return row.Id;
            });
            if (ids.length < 1) {
                layer.msg('请至少选中一行', {
                    time: 4000, //20s后自动关闭
                });
            } else {
                Delete(ids.join(","));
            }
        });
        //导出
        $("#exportExcel").on('click', function () {
            var ids = $.map($('#MachineDetailTable').bootstrapTable('getSelections'), function (row) {
                return row.Id;
            });
            Export(ids)
        });
        //2.初始化Button的点击事件
        var oButtonInit = new ButtonInit();
        oButtonInit.Init();
        //用户
        //1.初始化商户Table
        var MachineDetailTablets = new MachineDetailTableInit();
        MachineDetailTablets.Init();
    });
    var ButtonInit = function () {
        var oInit = new Object();
        var postdata = {};
        oInit.Init = function () {
            //初始化页面上面的按钮事件
        };
        return oInit;
    };
    var MachineDetailTableInit = function () {
        var oTableInit = new Object();
        //初始化Table
        oTableInit.Init = function () {
            $('#MachineDetailTable').bootstrapTable({
                url: '/MachineDetail/GetMachineDetailGrid',
                ajaxOptions: { async: true, timeout: 10000 },
                method: 'get',
                //toolbar: '#toolbar',              //工具按钮用哪个容器
                striped: false,
                toolbar: false,                     //是否显示行间隔色
                cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                pagination: true,                   //是否显示分页（*）
                silentSort: true,
                sortStable: true,
                sortable: true,                     //是否启用排序
                sortOrder: "asc",                   //排序方式
                queryParams: oTableInit.queryParams,//这里的键的名字和控制器的变量名必须一致，这边改动，控制器也需要改成一样的
                sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
                pageNumber: 1,                      //初始化加载第一页，默认第一页,并记录
                pageSize: 10,                       //每页的记录行数（*）
                pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                search: false,                      //是否显示表格搜索
                strictSearch: true,
                showColumns: false,                  //是否显示所有的列（选择显示的列）
                showRefresh: false,                  //是否显示刷新按钮
                minimumCountColumns: 2,             //最少允许的列数
                clickToSelect: true,                //是否启用点击选中行
                height: "auto",                     //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                uniqueId: "Id",                     //每一行的唯一标识，一般为主键列
                showToggle: false,                  //是否显示详细视图和列表视图的切换按钮
                cardView: false,                    //是否显示详细视图
                detailView: false,                  //是否显示父子表
                columns: [
                    {
                        checkbox: true,
                        visible: true              //是否显示复选框
                    },
                    {
                        field: 'StoreName',
                        title: '所属Market',
                        sortable: true
                    },
                    {
                        field: 'MachineName',
                        title: '机器名称',
                        sortable: true
                    },
                    {
                        field: 'MachineNo',
                        title: '机器编号',
                        sortable: true
                    },
                    {
                        field: 'PassageNumber',
                        title: '通道编号',
                        sortable: true
                    },
                    {
                        field: 'ProductName_CH',
                        title: '商品名称',
                        sortable: true
                    },
                    {
                        field: 'CreateUser',
                        title: '添加人'
                    },
                    {
                        field: 'CredateTime',
                        title: '添加时间',
                        formatter: function (value, row, index) {
                            return Common.DateFormat(value)
                        }
                    }
                ]
            });
        };
        //得到查询的参数
        oTableInit.queryParams = function (params) {
            var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
                limit: params.limit,   //页面大小
                offset: params.offset,  //页码
                sort: params.sort,      //排序列名
                sortOrder: params.order, //排位命令（desc，asc）
                machinemame: $("#MachineName").val(),//名称
                machinenumber: $("#MachineNumber").val(),
                productid: $("#ProductId").val()
            };
            return temp;
        };
        return oTableInit;
    };
</script>

<script>
    var CreateMachineDetail = function () {
        layer.open({
            type: 2,
            title: '添加通道',
            shadeClose: true,
            shade: 0.8,
            area: ['20%', '40%'],
            content: 'Add'
        })
    }
    var EditMachineDetail = function (id) {
        layer.open({
            type: 2,
            title: '编辑通道',
            shadeClose: true,
            shade: 0.8,
            area: ['20%', '40%'],
            content: 'Edit?id=' + id
        })
    }

    //删除
    var Delete = function (ids) {
        layer.confirm('您确定要删除吗？', {
            title: '提示',
            move: false,
            anim: 1, //默认动画风格
            btn: ['确定', '取消'] //按钮
        }, function () {
            $.ajax({
                type: 'Post',
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                data: JSON.stringify({ ids: ids }),
                async: true,
                url: 'Delete',
                success: function (result) {
                    if (result.Success) {
                        layer.closeAll('dialog');
                        layer.msg('删除成功！', {
                            time: 2000,
                        });
                        $("#MachineDetailTable").bootstrapTable('refresh', { url: '/MachineDetail/GetMachineDetailGrid' });
                    } else {
                        layer.open({
                            title: '提示',
                            content: '删除失败！',
                            move: false,
                            btn: "知道了"
                        });
                    }
                },
                error: function (result) {
                    console.log(result)
                }
            })
        });
    };

     //导出
    var Export = function (ids) {
        $.ajax({
            type: "Post",
            url: '@Url.Action("ExportExcel", "MachineDetail", new { area = "" })',
            dataType: "json",
            data: {
                ids: ids
            },
            success: function (result) {
                if (result.Success) {
                    window.location.target = "_blank";
                    window.location.href = result.Data;
                } else {
                    layer.open({
                        title: '提示',
                        content: result.ErrorMsg,
                        move: false,
                        btn: "知道了"
                    });
                }
            }
        })
    }
</script>