VendM.Web/Areas/Basics/Controllers/MachineController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using VendM.Core;
using VendM.Model.DataModelDto;
using VendM.Model.EnumModel;
using VendM.Service;
using VendM.Service.BasicsService;
using VendM.Web.Authorization;
using VendM.Web.BaseApplication;
using VendM.Web.Models;
namespace VendM.Web.Areas.Basics.Controllers
{
    public class MachineController : ServicedController<MachineService>
    {

        #region VendM.Web.Areas.Basics.Controllers
        /// <summary>
        /// 首页
        /// </summary>
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.FaultType = GetSelectList(typeof(FaultEnum), true);
            ViewBag.StatusType = GetSelectList(typeof(StatusEnum), true);
            return View();
        }
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetMachineGrid(int limit, int offset, string sort, string sortOrder, string name, string code, string status, string fault)
        {
            TablePageParameter gp = new TablePageParameter() { Limit = limit, Offset = offset, SortName = sort, SortOrder = sortOrder };
            List<MachineDto> machineList = Service.GetMachineGrid(gp, name, code, status,fault);
            return Json(new { total = gp.TotalCount, rows = machineList }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 新建
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult Add()
        {
            ViewData["StoreList"] = GetStoreSelectList("-1", "请选择");
            ViewBag.StatusType = GetSelectList(typeof(StatusEnum), true);
            return View();
        }

        /// <summary>
        /// Market
        /// </summary>
        /// <param name="emptyKey"></param>
        /// <param name="emptyValue"></param>
        /// <param name="isAll"></param>
        /// <returns></returns>
        public List<SelectListItem> GetStoreSelectList(string emptyKey, string emptyValue, bool isAll = false)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            if (emptyKey != null)
            {
                listItems.Add(new SelectListItem { Text = emptyValue, Value = emptyKey });
            }
            List<StoreDto> lists = new StoreService().GetStoreGrid();
            foreach (var item in lists)
            {
                listItems.Add(new SelectListItem { Text = item.Name, Value = item.Id.ToString() });
            }
            return listItems;
        }

        //添加机器设备 同时也会加一条机器库存
        [HttpPost]
        public ActionResult Add(MachineDto Machinedto)
        {
            ResultJsonInfo resultJsonInfo = new ResultJsonInfo() { Data = "", ErrorMsg = "", Success = true };
            try
            {
                if (ModelState.IsValid)
                {
                    if (Service.AddMachine(Machinedto, ServiceHelper.GetCurrentUser().UserName))
                    {
                        return this.Ajax_JGClose();
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                string msg = ex.Message;
                throw;
            }
        }
        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.StatusType = GetSelectList(typeof(StatusEnum), true);
            var entity = Service.Get(id);
            ViewBag.StoreList = new StoreService().GetStoreList("", "").ToSelectList(entity.StoreId);
            ViewBag.FaultType = EnumExtension.GetSelectList(typeof(FaultEnum), "", "故障类型...").ToSelectList(entity.FaultType);
            ViewData.Model = entity;
            return View();
        }
        [HttpPost]
        public ActionResult Edit(MachineDto Machinedto)
        {
            string errorMsg = "";
            if (ModelState.IsValid)
            {
                Machinedto.UpdateUser = ServiceHelper.GetCurrentUser().LoginName;
                Machinedto.UpdateTime = DateTime.Now;
                if (Service.Update(Machinedto))
                {
                    return this.Ajax_JGClose();
                }
            }
            else
            {
                var entity = Service.Get(Machinedto.Id);
                ViewBag.StoreList = new StoreService().GetStoreList("", "").ToSelectList(entity.StoreId);
                ViewData.Model = entity;
            }
            @ViewBag.errorMsg = errorMsg;
            return View();
        }

        /// <summary>
        /// 编辑故障类型
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpGet]
        public ActionResult SetFault(int id)
        {
            var entity = Service.Get(id);
            ViewBag.FaultType = EnumExtension.GetSelectList(typeof(FaultEnum), "", "故障类型...").ToSelectList(entity.FaultType);
            ViewData.Model = entity;
            return View();
        }

        /// <summary>
        /// 编辑编辑故障类型
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpPost]
        public ActionResult SetFault(MachineDto Machinedto)
        {
            string errorMsg = "";
            if (ModelState.IsValid)
            {
                if (Service.SetFault(Machinedto.Id, Machinedto.FaultType, Machinedto.FaultTime, Machinedto.HandleTime))
                {
                    return this.Ajax_JGClose();
                }
            }
            @ViewBag.errorMsg = errorMsg;
            return View();
        }
        
        /// <summary>
        /// 删除
        /// </summary>
        /// <returns>返回操作结果</returns>
        [HttpPost]
        public JsonResult Delete(string ids)
        {
            ResultJsonInfo resultJsonInfo = new ResultJsonInfo() { Data = "", ErrorMsg = "", Success = true };
            try
            {
                if (!Service.Deletes(ids, ServiceHelper.GetCurrentUser().LoginName))
                {
                    resultJsonInfo.Success = false;
                    resultJsonInfo.Data = "请先删除该机器的通道";
                }
            }
            catch (Exception ex)
            {
                resultJsonInfo.Success = false;
                resultJsonInfo.ErrorMsg = ex.Message;
            }
            return Json(resultJsonInfo, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

VendM.Web/Areas/Basics/Views/Machine/Add.cshtml
@{
    ViewBag.Title = "Add";
}
@model VendM.Model.DataModelDto.MachineDto
@using (Html.BeginForm("Add", "Machine", FormMethod.Post))
{
    <div style="margin: 15px; border: 1px">
        <div class="form-group">
            <label for="name">Market名称</label>
            @Html.DropDownListFor(m => m.StoreId, ViewData["StoreList"] as List<SelectListItem>, new { @class = "form-control", placeholder = "Market名称", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">机器名称</label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "机器名称", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">编号</label>
            @Html.TextBoxFor(m => m.MachineNo, new { @class = "form-control", placeholder = "编号", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">密码</label>
            @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "密码", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">机器狀態</label>
            @Html.DropDownListFor(m => m.Status, (IEnumerable<SelectListItem>)ViewBag.StatusType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">地址</label>
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "地址", required = "required" })
        </div>
        <div>
            <div>
                <button type="submit" class="btn btn-primary btn-primary-subbtn">提交</button>
            </div>
        </div>
    </div>
}
<script>

    /*自定义validate*/
    var rules = {
        Name: {
            required: true
        },
        Code: {
            required: true,
            remote: "/Machine/ValidateName"
        },
        ProfileId: "required",
        Address: "required",
        StoreId: {
            required: true,
            min: 0
        }
    },
        messages = {
            Name: {
                required: "请输入機器名稱"
            },
            Code: {
                required: "请输入機器编号",
                remote: "已存在機器编号"
            },
            ProfileId: {
                required: "请输入ProfileId"
            },
            Address: {
                required: "请输入地址"
            }, StoreId: {
                required: "请选择Market",
                min: "请选择Market"
            }
        };
    $(document).ready(function () {
      
        // 在键盘按下并释放及提交后验证提交表单
        $("form").validate({
            rules: rules,
            messages: messages
        });
    });
</script>

VendM.Web/Areas/Basics/Views/Machine/Edit.cshtml
@model VendM.Model.DataModelDto.MachineDto
@{
    ViewBag.Title = "Edit";
}

<script type="text/javascript">

    $(document).ready(function () {
        $("form").validate();
    });
   
</script>
@using (Html.BeginForm())
{
    <div style="margin: 15px; border: 1px">
        <div class="form-group">
            <label for="name">Market名称</label>
                @Html.DropDownListFor(m => m.StoreId, (IEnumerable<SelectListItem>)ViewBag.StoreList, new { @class = "form-control", placeholder = "Market名称", required = "required" })
            </div>
        <div class="form-group">
            <label for="name">机器名称</label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "机器名称", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">编号</label>
            @Html.TextBoxFor(m => m.MachineNo, new { @class = "form-control", placeholder = "编号", required = "required" })
        </div>
        <div class="form-group">
            <label for="name">密码</label>
            @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "密码", required = "required" })
            @Html.HiddenFor(m => m.Id)
        </div>
        <div class="form-group">
            <label for="name">机器狀態</label>
            @Html.DropDownListFor(m => m.Status, (IEnumerable<SelectListItem>)ViewBag.StatusType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">地址</label>
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "地址", required = "required" })
        </div>
        <div>
            <button type="submit" class="btn btn-primary btn-primary-subbtn">提交</button>
        </div>
    </div>
}

VendM.Web/Areas/Basics/Views/Machine/SetFault.cshtml
@{
    ViewBag.Title = "SetFault";
}


@model VendM.Model.DataModelDto.MachineDto

<script type="text/javascript">
    

    $(document).ready(function () {
        $("#FaultTime").datetimepicker({
            format: 'yyyy-mm-dd hh: ii'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        $("#HandleTime").datetimepicker({
            format: 'yyyy-mm-dd hh: ii'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });
        $("form").validate();
    });

</script>
@using (Html.BeginForm())
{
    <div style="margin: 15px; border: 1px">
        <div class="form-group">
            <label for="name">故障类型</label>
            @Html.DropDownListFor(m => m.FaultType, (IEnumerable<SelectListItem>)ViewBag.FaultType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">故障时间</label>
            @Html.TextBoxFor(m => m.FaultTime, new { @class = "form-control", placeholder = "故障时间"})
        </div>
        <div class="form-group">
            <label for="name">处理时间</label>
            @Html.TextBoxFor(m => m.HandleTime, new { @class = "form-control", placeholder = "处理时间" })
        </div>
        <div>
            <button type="submit" class="btn btn-primary btn-primary-subbtn">提交</button>
        </div>
    </div>
}